[Interface]
PrivateKey = xxxx
Address = 10.69.69.1/24
ListenPort = 51820
MTU = 1360

PostUp = sysctl -w net.ipv4.ip_forward=1

# -----------------------------
# DNAT: Public → Windows WG IP
# -----------------------------
PostUp = iptables -t nat -A PREROUTING -p udp --dport 7777  -j DNAT --to-destination 10.69.69.2:7777
PostUp = iptables -t nat -A PREROUTING -p udp --dport 27015 -j DNAT --to-destination 10.69.69.2:27015

# -----------------------------
# FORWARD: Allow traffic
# -----------------------------
PostUp = iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
PostUp = iptables -A FORWARD -i eth0 -o wg0 -p udp -d 10.69.69.2 --dport 7777  -j ACCEPT
PostUp = iptables -A FORWARD -i eth0 -o wg0 -p udp -d 10.69.69.2 --dport 27015 -j ACCEPT
PostUp = iptables -A FORWARD -i wg0  -o eth0 -j ACCEPT

# -----------------------------
# SNAT: Hide client IPs from Windows
# -----------------------------
PostUp = iptables -t nat -A POSTROUTING -p udp -d 10.69.69.2 --dport 7777  -j MASQUERADE
PostUp = iptables -t nat -A POSTROUTING -p udp -d 10.69.69.2 --dport 27015 -j MASQUERADE

#PostUp = iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE


# -----------------------------
# Cleanup on shutdown
# -----------------------------
PostDown = iptables -t nat -D PREROUTING -p udp --dport 7777  -j DNAT --to-destination 10.69.69.2:7777
PostDown = iptables -t nat -D PREROUTING -p udp --dport 27015 -j DNAT --to-destination 10.69.69.2:27015

PostDown = iptables -D FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
PostDown = iptables -D FORWARD -i eth0 -o wg0 -p udp -d 10.69.69.2 --dport 7777 -j ACCEPT
PostDown = iptables -D FORWARD -i eth0 -o wg0 -p udp -d 10.69.69.2 --dport 27015 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0  -o eth0 -j ACCEPT

PostDown = iptables -t nat -D POSTROUTING -p udp -d 10.69.69.2 --dport 7777  -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -p udp -d 10.69.69.2 --dport 27015 -j MASQUERADE

#PostDown = iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE


[Peer]
PublicKey = xxxx
AllowedIPs = 10.69.69.2/32
